POST http://localhost:8000/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "admin@mail.com",
    "password": "password"
}

### Get All Books
GET http://localhost:8000/api/books
Authorization: Bearer 2|yGG24gCsStDhNrKMvDXlac9VAm00vfYk1syNTSgX3b616755
Accept: application/json

### Add New Book
POST http://localhost:8000/api/books
Authorization: Bearer 2|yGG24gCsStDhNrKMvDXlac9VAm00vfYk1syNTSgX3b616755
Content-Type: application/json
Accept: application/json

{
    "judul": "Filosofi Teras",
    "penulis": "Henry Manampiring",
    "stok": 12
}

### Pinjam Buku 
POST http://localhost:8000/api/borrow
Authorization: Bearer 2|yGG24gCsStDhNrKMvDXlac9VAm00vfYk1syNTSgX3b616755
Content-Type: application/json
Accept: application/json

{
    "book_id": 1
}

### Kembali Buku
POST http://localhost:8000/api/return
Authorization: Bearer 2|yGG24gCsStDhNrKMvDXlac9VAm00vfYk1syNTSgX3b616755
Content-Type: application/json
Accept: application/json

{
    "transaction_id": 2
}